import React from "react";

import "./styles/globals.css";

import Nav from "./components/Nav";

import { MediaProvider } from "./context/MediaContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Nav />
        </header>
        <MediaProvider>{children} </MediaProvider>
      </body>
    </html>
  );
}
