AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  FrontendLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MoodMelodyFrontendFunction
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/mood-melody-aws:frontend-latest"
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          NEXT_PUBLIC_API_URL_0: https://pn39vm6kg3.execute-api.eu-north-1.amazonaws.com/prod
          NEXT_PUBLIC_API_URL_1: https://pn39vm6kg3.execute-api.eu-north-1.amazonaws.com/prod/api/images
          NEXT_PUBLIC_API_URL_2: https://pn39vm6kg3.execute-api.eu-north-1.amazonaws.com/prod/api/musics
          NEXT_PUBLIC_API_URL_3: https://pn39vm6kg3.execute-api.eu-north-1.amazonaws.com/prod/api/test
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
              - Effect: Allow
                Action:
                  - apigateway:Invoke
                  - apigateway:ManageConnections
                Resource: "*"

Outputs:
  FrontendApiUrl:
    Description: "URL for the frontend API Gateway"
    Value: !Sub "https://${FrontendLambdaFunction.HttpApiEvent.ApiId}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: FrontendApiUrl
