AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  FrontendLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MoodMelodyFrontendFunction
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/mood-melody-aws:frontend-{{resolve:ssm:/mood-melody/frontend-timestamp}}"
      MemorySize: 512
      Timeout: 300
      Architectures:
        - x86_64
      Events:
        HttpEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+} # Catch-all route
            Method: ANY
            ApiId: !Ref ServerlessHttpApi

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
              - Effect: Allow
                Action:
                  - apigateway:Invoke
                  - apigateway:ManageConnections
                Resource: "*"
  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'GET,OPTIONS,POST'"
        AllowOrigins: "'*'"
      DefaultRouteSettings:
        DetailedMetricsEnabled: True

  ApiGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ServerlessHttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FrontendLambdaFunction.Arn}:$stageVariables.lambdaAlias/invocations"
      PayloadFormatVersion: "2.0"

Outputs:
  FrontendApiUrl:
    Description: "URL for the frontend API Gateway"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
    Export:
      Name: FrontendApiUrl
