AWSTemplateFormatVersion: "2010-09-09"

Resources:
  UserFeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "UserFeedbackTable"
      AttributeDefinitions:
        - AttributeName: "submissionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "submissionId"
          KeyType: "HASH"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true

Outputs:
  UserFeedbackTableArn:
    Description: "ARN of the UserFeedbackTable"
    Value: !GetAtt UserFeedbackTable.Arn
    Export:
      Name: UserFeedbackTableArn

  UserFeedbackTableName:
    Description: "Name of the DynamoDB UserFeedbackTable"
    Value: !Ref UserFeedbackTable
    Export:
      Name: UserFeedbackTableName
