name: Build and Push Frontend

on:
  repository_dispatch:
    types: [build-frontend]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          BACKEND_API_URL: ${{ github.event.client_payload.BACKEND_API_URL }}
        run: |
          echo "BACKEND_API_URL=${BACKEND_API_URL}" >> $GITHUB_ENV
          echo "BACKEND_API_URL ===== , ${BACKEND_API_URL}"

      - name: Generate timestamp
        id: vars
        # run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build and push frontend Docker image
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
          REPO_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/mood-melody-aws
          BACKEND_API_URL: ${{ env.BACKEND_API_URL }}

        run: |

          echo "BACKEND_API_UR from build and push fronten image step ========= ${BACKEND_API_URL}"
          docker build \
            --build-arg NEXT_PUBLIC_API_URL_0=${BACKEND_API_URL}/api/images \
            --build-arg NEXT_PUBLIC_API_URL_1=${BACKEND_API_URL}/api/musics \
            -t mood-melody-aws:frontend-${TIMESTAMP} \
            -t mood-melody-aws:frontend-latest \
            ./frontend

          docker tag mood-melody-aws:frontend-${TIMESTAMP} ${REPO_URI}:frontend-${TIMESTAMP}
          docker tag mood-melody-aws:frontend-latest ${REPO_URI}:frontend-latest
          docker push ${REPO_URI}:frontend-${TIMESTAMP}
          docker push ${REPO_URI}:frontend-latest

      - name: Verify frontend image exists
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
        run: |
          aws ecr describe-images --repository-name mood-melody-aws --image-ids imageTag=frontend-${TIMESTAMP}

      - name: Trigger CodePipeline Stage
        env:
          AWS_REGION: eu-north-1
          LAMBDA_FUNCTION_NAME: TriggerSpecificStage
          PIPELINE_NAME: mood-melody
          STAGE_NAME: Deploy-frontend
        run: |
          echo "Invoking Lambda function to trigger CodePipeline stage..."
          echo "AWS Region: $AWS_REGION"
          echo "Lambda Function Name: $LAMBDA_FUNCTION_NAME"
          echo "Pipeline Name: $PIPELINE_NAME"
          echo "Stage Name: $STAGE_NAME"


          aws lambda invoke \
            --function-name TriggerSpecificStage \
            --region eu-north-1 \
            --cli-binary-format raw-in-base64-out \
            --payload '{"pipeline_name":"mood-melody", "stage_name":"Deploy-frontend"}' \
            response.json

          echo "Lambda invocation response:"
          cat response.json
