name: Build and Push Frontend

on:
  repository_dispatch:
    types: [build-frontend]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          BACKEND_API_URL: ${{ github.event.client_payload.BACKEND_API_URL }}
          UNIQUE_ID: ${{ github.event.client_payload.UNIQUE_ID }}
        run: |
          echo "BACKEND_API_URL=${BACKEND_API_URL}" >> $GITHUB_ENV
          echo "UNIQUE_ID=${UNIQUE_ID}" >> $GITHUB_ENV
          echo "BACKEND_API_URL ===== , ${BACKEND_API_URL}"
          echo "UNIQUE_ID ===== , ${UNIQUE_ID}"

      - name: Generate timestamp
        id: vars
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::536560382233:role/jinghuan-github-actions-OIDC-role
          role-session-name: OIDCSession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build and push frontend Docker image
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
          REPO_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mood-melody-aws
          BACKEND_API_URL: ${{ env.BACKEND_API_URL }}
        run: |
          echo "BACKEND_API_UR from build and push fronten image step ========= ${BACKEND_API_URL}"
          docker build \
            --build-arg NEXT_PUBLIC_API_URL_0=${BACKEND_API_URL}/api/images \
            --build-arg NEXT_PUBLIC_API_URL_1=${BACKEND_API_URL}/api/musics \
            -t mood-melody-aws:frontend-${TIMESTAMP} \
            -t mood-melody-aws:frontend-latest \
            ./frontend

          docker tag mood-melody-aws:frontend-${TIMESTAMP} ${REPO_URI}:frontend-${TIMESTAMP}
          docker tag mood-melody-aws:frontend-latest ${REPO_URI}:frontend-latest
          docker push ${REPO_URI}:frontend-${TIMESTAMP}
          docker push ${REPO_URI}:frontend-latest

      - name: Verify frontend image exists
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
        run: |
          aws ecr describe-images --repository-name mood-melody-aws --image-ids imageTag=frontend-${TIMESTAMP}

      - name: Signal Lambda to trigger next stage of stage Retrieve-bakendApiUrl-trigger-frontend-githubActions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          UNIQUE_ID: ${{ env.UNIQUE_ID }}
        run: |
          echo '{"signal": true, "unique_id": "'${UNIQUE_ID}'"}' > signal.json
          aws s3 cp signal.json s3://mood-melody-signal-bucket/github-action-signal-${UNIQUE_ID}.json
