name: Build and Push Frontend

on:
  repository_dispatch:
    types: [build-frontend]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::536560382233:role/jinghuan-github-actions-OIDC-role
          role-session-name: OIDCSession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up environment variables
        env:
          BACKEND_API_URL: ${{ github.event.client_payload.BACKEND_API_URL }}
          UNIQUE_ID: ${{ github.event.client_payload.UNIQUE_ID }}

        run: |
          echo "BACKEND_API_URL=${BACKEND_API_URL}" >> $GITHUB_ENV
          echo "UNIQUE_ID=${UNIQUE_ID}" >> $GITHUB_ENV
          echo "BACKEND_API_URL ===== , ${BACKEND_API_URL}"
          echo "UNIQUE_ID ===== , ${UNIQUE_ID}"

      - name: Generate timestamp
        id: vars
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Store Timestamp in Parameter Store
        run: |
          aws ssm put-parameter --name "/mood-melody/frontend-timestamp" --value ${{ env.TIMESTAMP }} --type String --overwrite --region ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build and push frontend Docker image
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
          REPO_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mood-melody-aws
          BACKEND_API_URL: ${{ env.BACKEND_API_URL }}
        run: |
          echo "BACKEND_API_URL from build and push frontend image step ========= ${BACKEND_API_URL}"
          docker build \
            --build-arg NEXT_PUBLIC_API_URL_0=${BACKEND_API_URL}/ \
            --build-arg NEXT_PUBLIC_API_URL_1=${BACKEND_API_URL}/api/images \
            --build-arg NEXT_PUBLIC_API_URL_2=${BACKEND_API_URL}/api/musics \
            --build-arg NEXT_PUBLIC_API_URL_3=${BACKEND_API_URL}/api/test \
            --build-arg NEXT_PUBLIC_API_URL_4=${BACKEND_API_URL}/api/sentimentanalysis \
            --build-arg NEXT_PUBLIC_API_URL_5=${BACKEND_API_URL}/api/saveuserfeedback \
            -t mood-melody-aws:frontend-${TIMESTAMP} \
            -t mood-melody-aws:frontend-latest \
            ./frontend

          docker tag mood-melody-aws:frontend-${TIMESTAMP} ${REPO_URI}:frontend-${TIMESTAMP}
          docker tag mood-melody-aws:frontend-latest ${REPO_URI}:frontend-latest
          docker push ${REPO_URI}:frontend-${TIMESTAMP}
          docker push ${REPO_URI}:frontend-latest

      - name: Verify frontend image exists
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
        run: |
          aws ecr describe-images --repository-name mood-melody-aws --image-ids imageTag=frontend-${TIMESTAMP}
          aws ecr describe-images --repository-name mood-melody-aws --image-ids imageTag=frontend-latest

      - name: Signal Lambda to trigger next stage of stage Retrieve-bakendApiUrl-trigger-frontend-githubActions
        if: success()
        run: |
          echo '{"signal": true, "unique_id": "'${UNIQUE_ID}'", "status": "success"}' > signal.json
          aws s3 cp signal.json s3://mood-melody-signal-bucket/github-action-signal-${UNIQUE_ID}.json

      - name: Signal failure to S3
        if: failure()
        run: |
          echo '{"signal": true, "unique_id": "'${UNIQUE_ID}'", "status": "failure"}' > signal.json
          aws s3 cp signal.json s3://mood-melody-signal-bucket/github-action-signal-${UNIQUE_ID}.json
